// Auto-generated by macro-tracker/tracker.ts — do not edit.
// Live macro signals grounding the research theses. Last updated: 2026-06-09

export type MacroSignal = {
  key: string;
  label: string;
  value: string;
  changePct: number | null;
  changeLabel: string;
  note: string;
  source: string;
  asOf: string;
};

export const macro: MacroSignal[] = [
  {
    "key": "us-electricity-demand",
    "label": "US electricity demand",
    "value": "11.48 TWh/day",
    "changePct": 2.7,
    "changeLabel": "YoY",
    "note": "The demand driver under the whole power chain: flat for a decade, now climbing. 30-day average, lower-48.",
    "source": "EIA (Form EIA-930)",
    "asOf": "2026-06-07"
  },
  {
    "key": "natural-gas",
    "label": "Natural gas (Henry Hub)",
    "value": "$3.18/MMBtu",
    "changePct": 9.2,
    "changeLabel": "30d",
    "note": "Fuel cost behind the gas-turbine buildout (Build and Serve).",
    "source": "CME via Yahoo Finance",
    "asOf": "2026-06-09"
  },
  {
    "key": "copper",
    "label": "Copper",
    "value": "$6.41/lb",
    "changePct": 0,
    "changeLabel": "30d",
    "note": "The conductor the buildout runs on (The Copper Squeeze).",
    "source": "CME via Yahoo Finance",
    "asOf": "2026-06-09"
  },
  {
    "key": "crude-oil",
    "label": "Crude oil (WTI)",
    "value": "$89.12/bbl",
    "changePct": -9.1,
    "changeLabel": "30d",
    "note": "Broad energy backdrop for the buildout theses.",
    "source": "CME via Yahoo Finance",
    "asOf": "2026-06-09"
  }
];
