// Auto-generated by macro-tracker/tracker.ts — do not edit.
// Live macro signals grounding the research theses. Last updated: 2026-09-11

export type MacroSignal = {
  key: string;
  label: string;
  value: string;
  changePct: number | null;
  changeLabel: string;
  note: string;
  source: string;
  asOf: string;
};

export const macro: MacroSignal[] = [
  {
    "key": "us-electricity-demand",
    "label": "US electricity demand",
    "value": "14.14 TWh/day",
    "changePct": 10.5,
    "changeLabel": "YoY",
    "note": "The demand driver under the whole power chain: flat for a decade, now climbing. 30-day average, lower-48.",
    "source": "EIA (Form EIA-930)",
    "asOf": "2026-09-09"
  },
  {
    "key": "natural-gas",
    "label": "Natural gas (Henry Hub)",
    "value": "$2.82/MMBtu",
    "changePct": 2,
    "changeLabel": "30d",
    "note": "Fuel cost behind the gas-turbine buildout (Build and Serve).",
    "source": "CME via Yahoo Finance",
    "asOf": "2026-09-11"
  },
  {
    "key": "copper",
    "label": "Copper",
    "value": "$6.59/lb",
    "changePct": -0.4,
    "changeLabel": "30d",
    "note": "The conductor the buildout runs on (The Copper Squeeze).",
    "source": "CME via Yahoo Finance",
    "asOf": "2026-09-11"
  },
  {
    "key": "crude-oil",
    "label": "Crude oil (WTI)",
    "value": "$101.23/bbl",
    "changePct": 21.7,
    "changeLabel": "30d",
    "note": "Broad energy backdrop for the buildout theses.",
    "source": "CME via Yahoo Finance",
    "asOf": "2026-09-11"
  }
];
