// Auto-generated by exotic/ledger.ts — do not edit.
// The observation ledger, exported for the /observatory page. Regenerated by
// tools-check, so the page follows the ledger. Last export: 2026-07-10T12:37:32.127Z

export type Observation = {
  target: string;
  obsDate: string;
  dataset: string | null;
  tmid: number | null;
  tmidErr: number | null;
  rprs: number | null;
  scatterPct: number | null;
  status: "reduced" | "validation" | "submitted" | "rejected";
  obscode: string | null;
  image: string | null;
  manifest: string | null;
  note: string | null;
};

// Number of reductions actually submitted to the AAVSO Exoplanet Database.
export const submittedCount = 0;

export const observations: Observation[] = [
  {
    "target": "HAT-P-27 b",
    "obsDate": "2026-07-06",
    "dataset": "MicroObservatory/Cecilia (public Image Directory), 63 usable of 75 frames",
    "tmid": 2461228.72,
    "tmidErr": 0.18,
    "rprs": 0.099,
    "scatterPct": 0.88,
    "status": "reduced",
    "obscode": null,
    "image": "/hat-p-27b-transit.png",
    "manifest": "/data/hat-p-27-20260706.manifest.txt",
    "note": "First successful reduction of fresh community data, and now cross-checked three ways. The same MObs night (2026-07-06) was reduced independently by three people: Richard Jaworski (WBoM/TransitLab: Tmid 2461228.708 +/- 0.0032, depth 1.44%), Joanna Puszkarska (EXOTIC, uploaded to AAVSO: Tmid 2461228.7 +/- 0.0071, depth 1.33%), and here by me (EXOTIC: Tmid 2461228.72 +/- 0.18, depth 0.98%). All three detect the transit and place its center within a few minutes of each other. Honest ranking: mine is the least precise of the three. My Tmid uncertainty is 25 to 50 times larger than theirs because clouds cut my first 40 minutes and left only 18 min of pre-ingress baseline to anchor the fit, and my depth reads low against both the others and the literature value (1.44%). A real detection, and the weakest of the three independent reductions, which is exactly what independent reductions are for. Not submitted (checkpoint holds); Joanna's is the one actually in AAVSO. This was also the first run to apply the CoRoT-2 lesson: triaged per-frame photon depth first, quarantined 12 cloudy frames, and re-ran once after the initial fit locked onto noise from 6-px-off coordinates."
  },
  {
    "target": "KELT-20 b",
    "obsDate": "2026-07-02",
    "dataset": "MicroObservatory/Cecilia (public Image Directory)",
    "tmid": null,
    "tmidErr": null,
    "rprs": null,
    "scatterPct": null,
    "status": "rejected",
    "obscode": null,
    "image": null,
    "manifest": "/data/kelt-20-20260702.manifest.txt",
    "note": "Saturated: KELT-20 is V=7.6, too bright for the 6-inch scope (target core clipped at 4095 ADU); bright comparison stars sat near the frame edge and tracked out over the 6h window. No usable transit fit. A real failure, kept in the record."
  },
  {
    "target": "CoRoT-2 b",
    "obsDate": "2026-06-30",
    "dataset": "MicroObservatory/Cecilia (public Image Directory)",
    "tmid": null,
    "tmidErr": null,
    "rprs": null,
    "scatterPct": null,
    "status": "rejected",
    "obscode": null,
    "image": null,
    "manifest": "/data/corot-2-20260630.manifest.txt",
    "note": "No detection: 18.4% residual scatter. V=12.2 star at only ~900 ADU above background in 20s frames - SNR too low for a 2.8% transit. Lesson: triage on per-frame photon depth, not just saturation."
  },
  {
    "target": "HAT-P-32 b",
    "obsDate": "2017-12-20",
    "dataset": "sample",
    "tmid": 2458107.71358,
    "tmidErr": 0.00094,
    "rprs": 0.1569,
    "scatterPct": 0.57,
    "status": "validation",
    "obscode": null,
    "image": "/hat-p-32b-transit.png",
    "manifest": null,
    "note": "Day-1 end-to-end validation on shipped MicroObservatory sample; not for submission (already in literature)"
  }
];
