// Auto-generated by exotic/ledger.ts — do not edit.
// The observation ledger, exported for the /observatory page. Regenerated by
// tools-check, so the page follows the ledger. Last export: 2026-07-06T18:37:25.457Z

export type Observation = {
  target: string;
  obsDate: string;
  dataset: string | null;
  tmid: number | null;
  tmidErr: number | null;
  rprs: number | null;
  scatterPct: number | null;
  status: "reduced" | "validation" | "submitted" | "rejected";
  obscode: string | null;
  image: string | null;
  note: string | null;
};

// Number of reductions actually submitted to the AAVSO Exoplanet Database.
export const submittedCount = 0;

export const observations: Observation[] = [
  {
    "target": "KELT-20 b",
    "obsDate": "2026-07-02",
    "dataset": "MicroObservatory/Cecilia (public Image Directory)",
    "tmid": null,
    "tmidErr": null,
    "rprs": null,
    "scatterPct": null,
    "status": "rejected",
    "obscode": null,
    "image": null,
    "note": "Saturated: KELT-20 is V=7.6, too bright for the 6-inch scope (target core clipped at 4095 ADU); bright comparison stars sat near the frame edge and tracked out over the 6h window. No usable transit fit. A real failure, kept in the record."
  },
  {
    "target": "CoRoT-2 b",
    "obsDate": "2026-06-30",
    "dataset": "MicroObservatory/Cecilia (public Image Directory)",
    "tmid": null,
    "tmidErr": null,
    "rprs": null,
    "scatterPct": null,
    "status": "rejected",
    "obscode": null,
    "image": null,
    "note": "No detection: 18.4% residual scatter. V=12.2 star at only ~900 ADU above background in 20s frames - SNR too low for a 2.8% transit. Lesson: triage on per-frame photon depth, not just saturation."
  },
  {
    "target": "HAT-P-32 b",
    "obsDate": "2017-12-20",
    "dataset": "sample",
    "tmid": 2458107.71358,
    "tmidErr": 0.00094,
    "rprs": 0.1569,
    "scatterPct": 0.57,
    "status": "validation",
    "obscode": null,
    "image": "/hat-p-32b-transit.png",
    "note": "Day-1 end-to-end validation on shipped MicroObservatory sample; not for submission (already in literature)"
  }
];
