// Auto-generated by price-tracker/tracker.ts — do not edit
// Last updated: 2026-06-05

export type TrackedPosition = {
  ticker: string;
  name: string;
  piece: string;
  signal: "BUY" | "HOLD" | "AVOID";
  entryPrice: number;
  entryDate: string;
  currentPrice: number | null;
  priceDate: string | null;
  changePercent: number | null;
};

export const positions: TrackedPosition[] = [
  {
    "ticker": "ETN",
    "name": "Eaton",
    "piece": "the-transformer-bottleneck",
    "signal": "BUY",
    "entryPrice": 369,
    "entryDate": "2026-04-09",
    "currentPrice": 395.94,
    "priceDate": "2026-06-05",
    "changePercent": 7.3
  },
  {
    "ticker": "GEV",
    "name": "GE Vernova",
    "piece": "the-transformer-bottleneck",
    "signal": "BUY",
    "entryPrice": 940,
    "entryDate": "2026-04-09",
    "currentPrice": 933.61,
    "priceDate": "2026-06-05",
    "changePercent": -0.7
  },
  {
    "ticker": "PWR",
    "name": "Quanta Services",
    "piece": "the-transformer-bottleneck",
    "signal": "HOLD",
    "entryPrice": 580,
    "entryDate": "2026-04-09",
    "currentPrice": 695.11,
    "priceDate": "2026-06-05",
    "changePercent": 19.8
  },
  {
    "ticker": "FCX",
    "name": "Freeport-McMoRan",
    "piece": "the-copper-squeeze",
    "signal": "BUY",
    "entryPrice": 66,
    "entryDate": "2026-04-10",
    "currentPrice": 63.37,
    "priceDate": "2026-06-05",
    "changePercent": -4
  },
  {
    "ticker": "SCCO",
    "name": "Southern Copper",
    "piece": "the-copper-squeeze",
    "signal": "HOLD",
    "entryPrice": 178,
    "entryDate": "2026-04-10",
    "currentPrice": 172.97,
    "priceDate": "2026-06-05",
    "changePercent": -2.8
  },
  {
    "ticker": "COPX",
    "name": "Global X Copper Miners ETF",
    "piece": "the-copper-squeeze",
    "signal": "BUY",
    "entryPrice": 82,
    "entryDate": "2026-04-10",
    "currentPrice": 80.64,
    "priceDate": "2026-06-05",
    "changePercent": -1.7
  },
  {
    "ticker": "BHP",
    "name": "BHP Group",
    "piece": "the-copper-squeeze",
    "signal": "HOLD",
    "entryPrice": 77,
    "entryDate": "2026-04-10",
    "currentPrice": 82.72,
    "priceDate": "2026-06-05",
    "changePercent": 7.4
  },
  {
    "ticker": "VRT",
    "name": "Vertiv Holdings",
    "piece": "the-heat-wall",
    "signal": "BUY",
    "entryPrice": 295,
    "entryDate": "2026-04-11",
    "currentPrice": 300.51,
    "priceDate": "2026-06-05",
    "changePercent": 1.9
  },
  {
    "ticker": "NVT",
    "name": "nVent Electric",
    "piece": "the-heat-wall",
    "signal": "BUY",
    "entryPrice": 131,
    "entryDate": "2026-04-11",
    "currentPrice": 162.86,
    "priceDate": "2026-06-05",
    "changePercent": 24.3
  },
  {
    "ticker": "MOD",
    "name": "Modine Manufacturing",
    "piece": "the-heat-wall",
    "signal": "HOLD",
    "entryPrice": 239,
    "entryDate": "2026-04-11",
    "currentPrice": 276.51,
    "priceDate": "2026-06-05",
    "changePercent": 15.7
  }
];

export function getPositionsForPiece(slug: string): TrackedPosition[] {
  return positions.filter((p) => p.piece === slug);
}
