// Auto-generated by price-tracker/tracker.ts — do not edit
// Last updated: 2026-07-01

export type TrackedPosition = {
  ticker: string;
  name: string;
  piece: string;
  signal: "BUY" | "HOLD" | "AVOID";
  entryPrice: number;
  entryDate: string;
  currentPrice: number | null;
  priceDate: string | null;
  changePercent: number | null;
};

export const positions: TrackedPosition[] = [
  {
    "ticker": "ETN",
    "name": "Eaton",
    "piece": "the-transformer-bottleneck",
    "signal": "BUY",
    "entryPrice": 369,
    "entryDate": "2026-04-09",
    "currentPrice": 415.17,
    "priceDate": "2026-07-01",
    "changePercent": 12.5
  },
  {
    "ticker": "GEV",
    "name": "GE Vernova",
    "piece": "the-transformer-bottleneck",
    "signal": "BUY",
    "entryPrice": 940,
    "entryDate": "2026-04-09",
    "currentPrice": 1132.35,
    "priceDate": "2026-07-01",
    "changePercent": 20.5
  },
  {
    "ticker": "PWR",
    "name": "Quanta Services",
    "piece": "the-transformer-bottleneck",
    "signal": "HOLD",
    "entryPrice": 580,
    "entryDate": "2026-04-09",
    "currentPrice": 690.8,
    "priceDate": "2026-07-01",
    "changePercent": 19.1
  },
  {
    "ticker": "FCX",
    "name": "Freeport-McMoRan",
    "piece": "the-copper-squeeze",
    "signal": "BUY",
    "entryPrice": 66,
    "entryDate": "2026-04-10",
    "currentPrice": 60.885,
    "priceDate": "2026-07-01",
    "changePercent": -7.8
  },
  {
    "ticker": "SCCO",
    "name": "Southern Copper",
    "piece": "the-copper-squeeze",
    "signal": "HOLD",
    "entryPrice": 178,
    "entryDate": "2026-04-10",
    "currentPrice": 170.33,
    "priceDate": "2026-07-01",
    "changePercent": -4.3
  },
  {
    "ticker": "COPX",
    "name": "Global X Copper Miners ETF",
    "piece": "the-copper-squeeze",
    "signal": "BUY",
    "entryPrice": 82,
    "entryDate": "2026-04-10",
    "currentPrice": 76.07,
    "priceDate": "2026-07-01",
    "changePercent": -7.2
  },
  {
    "ticker": "BHP",
    "name": "BHP Group",
    "piece": "the-copper-squeeze",
    "signal": "HOLD",
    "entryPrice": 77,
    "entryDate": "2026-04-10",
    "currentPrice": 82.37,
    "priceDate": "2026-07-01",
    "changePercent": 7
  },
  {
    "ticker": "VRT",
    "name": "Vertiv Holdings",
    "piece": "the-heat-wall",
    "signal": "BUY",
    "entryPrice": 295,
    "entryDate": "2026-04-11",
    "currentPrice": 313.12,
    "priceDate": "2026-07-01",
    "changePercent": 6.1
  },
  {
    "ticker": "NVT",
    "name": "nVent Electric",
    "piece": "the-heat-wall",
    "signal": "BUY",
    "entryPrice": 131,
    "entryDate": "2026-04-11",
    "currentPrice": 160,
    "priceDate": "2026-07-01",
    "changePercent": 22.1
  },
  {
    "ticker": "MOD",
    "name": "Modine Manufacturing",
    "piece": "the-heat-wall",
    "signal": "HOLD",
    "entryPrice": 239,
    "entryDate": "2026-04-11",
    "currentPrice": 248.305,
    "priceDate": "2026-07-01",
    "changePercent": 3.9
  },
  {
    "ticker": "SMEGF",
    "name": "Siemens Energy (ADR)",
    "piece": "build-and-serve",
    "signal": "BUY",
    "entryPrice": 180.45,
    "entryDate": "2026-06-08",
    "currentPrice": 182.45,
    "priceDate": "2026-07-01",
    "changePercent": 1.1
  },
  {
    "ticker": "MHVYF",
    "name": "Mitsubishi Heavy Industries (ADR)",
    "piece": "build-and-serve",
    "signal": "HOLD",
    "entryPrice": 23.24,
    "entryDate": "2026-06-08",
    "currentPrice": 22.75,
    "priceDate": "2026-06-30",
    "changePercent": -2.1
  }
];

export function getPositionsForPiece(slug: string): TrackedPosition[] {
  return positions.filter((p) => p.piece === slug);
}
