// Auto-generated by price-tracker/tracker.ts — do not edit
// Last updated: 2026-09-11

export type TrackedPosition = {
  ticker: string;
  name: string;
  piece: string;
  signal: "BUY" | "HOLD" | "AVOID";
  entryPrice: number;
  entryDate: string;
  currentPrice: number | null;
  priceDate: string | null;
  changePercent: number | null;
};

export const positions: TrackedPosition[] = [
  {
    "ticker": "ETN",
    "name": "Eaton",
    "piece": "the-transformer-bottleneck",
    "signal": "BUY",
    "entryPrice": 369,
    "entryDate": "2026-04-09",
    "currentPrice": 425.37,
    "priceDate": "2026-09-11",
    "changePercent": 15.3
  },
  {
    "ticker": "GEV",
    "name": "GE Vernova",
    "piece": "the-transformer-bottleneck",
    "signal": "HOLD",
    "entryPrice": 940,
    "entryDate": "2026-04-09",
    "currentPrice": 957.27,
    "priceDate": "2026-09-11",
    "changePercent": 1.8
  },
  {
    "ticker": "PWR",
    "name": "Quanta Services",
    "piece": "the-transformer-bottleneck",
    "signal": "HOLD",
    "entryPrice": 580,
    "entryDate": "2026-04-09",
    "currentPrice": 650.58,
    "priceDate": "2026-09-11",
    "changePercent": 12.2
  },
  {
    "ticker": "FCX",
    "name": "Freeport-McMoRan",
    "piece": "the-copper-squeeze",
    "signal": "HOLD",
    "entryPrice": 66,
    "entryDate": "2026-04-10",
    "currentPrice": 71.07,
    "priceDate": "2026-09-11",
    "changePercent": 7.7
  },
  {
    "ticker": "SCCO",
    "name": "Southern Copper",
    "piece": "the-copper-squeeze",
    "signal": "HOLD",
    "entryPrice": 178,
    "entryDate": "2026-04-10",
    "currentPrice": 193.49,
    "priceDate": "2026-09-11",
    "changePercent": 8.7
  },
  {
    "ticker": "COPX",
    "name": "Global X Copper Miners ETF",
    "piece": "the-copper-squeeze",
    "signal": "BUY",
    "entryPrice": 82,
    "entryDate": "2026-04-10",
    "currentPrice": 88.53,
    "priceDate": "2026-09-11",
    "changePercent": 8
  },
  {
    "ticker": "BHP",
    "name": "BHP Group",
    "piece": "the-copper-squeeze",
    "signal": "HOLD",
    "entryPrice": 77,
    "entryDate": "2026-04-10",
    "currentPrice": 87.15,
    "priceDate": "2026-09-11",
    "changePercent": 13.2
  },
  {
    "ticker": "VRT",
    "name": "Vertiv Holdings",
    "piece": "the-heat-wall",
    "signal": "BUY",
    "entryPrice": 295,
    "entryDate": "2026-04-11",
    "currentPrice": 257.06,
    "priceDate": "2026-09-11",
    "changePercent": -12.9
  },
  {
    "ticker": "NVT",
    "name": "nVent Electric",
    "piece": "the-heat-wall",
    "signal": "BUY",
    "entryPrice": 131,
    "entryDate": "2026-04-11",
    "currentPrice": 162.38,
    "priceDate": "2026-09-11",
    "changePercent": 24
  },
  {
    "ticker": "MOD",
    "name": "Modine Manufacturing",
    "piece": "the-heat-wall",
    "signal": "BUY",
    "entryPrice": 239,
    "entryDate": "2026-04-11",
    "currentPrice": 189.3,
    "priceDate": "2026-09-11",
    "changePercent": -20.8
  },
  {
    "ticker": "SMEGF",
    "name": "Siemens Energy (ADR)",
    "piece": "build-and-serve",
    "signal": "BUY",
    "entryPrice": 180.45,
    "entryDate": "2026-06-08",
    "currentPrice": 165.638,
    "priceDate": "2026-09-11",
    "changePercent": -8.2
  },
  {
    "ticker": "MHVYF",
    "name": "Mitsubishi Heavy Industries (ADR)",
    "piece": "build-and-serve",
    "signal": "HOLD",
    "entryPrice": 23.24,
    "entryDate": "2026-06-08",
    "currentPrice": 24.15,
    "priceDate": "2026-09-11",
    "changePercent": 3.9
  }
];

export function getPositionsForPiece(slug: string): TrackedPosition[] {
  return positions.filter((p) => p.piece === slug);
}
