// Auto-generated by postcards/review.ts export. Do not edit by hand.
export type Postcard = { id: number; name: string | null; message: string; date: string };
export const postcards: Postcard[] = [];
