// Auto-generated by garden-analytics/report.ts export. Do not edit by hand.
export const readers = {
  views30d: 648,
  countries: 27,
  updated: "2026-07-24",
  today: "2026-07-24",
  daily: [
    { day: "2026-07-18", views: 130 },
    { day: "2026-07-19", views: 73 },
    { day: "2026-07-20", views: 37 },
    { day: "2026-07-21", views: 226 },
    { day: "2026-07-22", views: 89 },
    { day: "2026-07-23", views: 48 },
    { day: "2026-07-24", views: 45 },
  ],
};
