export type ResearchSource = {
  title: string;
  url: string;
  author?: string;
};

export type ResearchPiece = {
  slug: string;
  date: string;
  title: string;
  excerpt: string;
  content: string[];
  sources: ResearchSource[];
};

export const pieces: ResearchPiece[] = [
  {
    slug: "week-one",
    date: "2026-04-16",
    title: "Week One",
    excerpt:
      "One week in, all three theses are holding — but the details are more interesting than the price moves. Half of planned US data centers delayed. A CEO died. A 50% tariff appeared. And the cooling sell-off confirmed itself as a buying opportunity.",
    content: [
      "This is the first portfolio review. The three research pieces — transformers, copper, cooling — were published between April 9 and April 11. A week later, 9 of 10 positions are green. ETN leads at +7.1%. MOD is the only red at -0.4%, narrowing from -1.5% yesterday. The portfolio is working.",
      "But the interesting thing about the first week isn't the price moves. It's the developments that confirm, complicate, or challenge the original theses. Price tells you what the market thinks today. Developments tell you whether the market will think differently tomorrow.",
      "--- Transformers: thesis strengthening ---",
      "The transformer bottleneck piece argued that AI's binding constraint is electrical infrastructure, not chips. One week later, the evidence has gotten harder to ignore. Nearly half of all planned US data center capacity has been canceled or delayed — not for lack of GPUs, but for lack of transformers and grid connections. Lead times have stretched further: 3 to 5 years for large power transformers, up from the 24-30 months I cited in the original piece.",
      "The companies are responding at scale. Eaton announced a $340 million investment in a new South Carolina transformer manufacturing facility, with production starting in 2027. That brings their cumulative North American manufacturing investment past $1 billion since 2023. Quanta Services held an investor day on April 4 projecting a $2.4 trillion total addressable market and targeting $21.60-$26.75 EPS by 2030. They're doubling their 765 kV transformer facility in Pennsylvania.",
      "GE Vernova reports Q1 earnings on April 22. Quanta reports April 30. These will be the first real test of whether backlog is converting to revenue at the rates guided. Watch the book-to-bill ratios.",
      "One development I didn't anticipate: China controls roughly 60% of global transformer manufacturing capacity, and US imports surged to over 8,000 units in 2025 — up from fewer than 1,500 in 2022. Bloomberg reported that the US data center expansion relies heavily on Chinese electrical equipment. This adds a geopolitical dimension the original piece didn't address. If tariffs or trade restrictions hit transformer imports, the bottleneck tightens further. Good for domestic manufacturers (GEV, ETN), potentially disruptive for the buildout timeline.",
      "No signal changes for the transformer positions. All three — BUY ETN, BUY GEV, HOLD PWR — hold.",
      "--- Copper: thesis holding, execution risk rising ---",
      "The copper thesis is structurally intact. Prices are at $6.07/lb, up 5% month-over-month and 30% year-over-year. Analysts project a 330,000-tonne deficit for 2026. The Grasberg mine in Indonesia — the world's second-largest — remains partially closed after a September mudslide, with the Block Cave section (70% of output) not expected to reopen until Q2. Every supply disruption tightens the thesis.",
      "But two material developments complicate the picture.",
      "First: Southern Copper's CEO Oscar Gonzalez Rocha died on April 7 after leading the company since 2004. Twenty-two years of institutional knowledge and industry relationships. No successor has been announced. The Tía María expansion project — $1.8 billion, 120,000 tonnes of annual capacity — is officially \"under review, not canceled\" per Peru's Mining Ministry. This is one of SCCO's key growth catalysts. A prolonged leadership transition could delay it further.",
      "I'm moving SCCO from BUY to HOLD. The fundamental copper thesis hasn't changed, but the company-specific execution risk has. A 22-year CEO can't be replaced without friction, and Tía María was already politically contentious before this. Hold if you own it. Wait for the successor announcement and clarity on the expansion timeline before adding.",
      "Second: on April 6, the Trump administration imposed new Section 232 tariffs on copper — 50% on pure copper and copper products, 25% on derivative articles. Domestic-content products get a lower 10% rate. This is structurally positive for US copper miners (FCX benefits from price support) but creates cost pressure on downstream copper users, including the very transformer manufacturers that the first thesis is built on. The tariff adds another feedback loop: copper tariffs raise transformer costs, which could slow data center construction, which is the demand driver for copper. The system is more interconnected than any single thesis captures.",
      "FCX reports Q1 earnings on April 23. Analysts expect 100% year-over-year EPS growth. Watch for Grasberg recovery timeline commentary and any guidance on tariff effects.",
      "Signal changes: SCCO moves from BUY to HOLD. FCX, COPX, BHP unchanged.",
      "--- Cooling: thesis confirmed ---",
      "The cooling thesis was the most contrarian of the three — arguing that the January CES sell-off (Modine -21% in a day) was a misreading of what Jensen Huang actually said. One week later, the thesis is confirmed on multiple fronts.",
      "Nvidia's Vera Rubin architecture, when it ships in H2 2026, will require 100% liquid cooling at 600 watts per rack. That's not \"water chillers are unnecessary\" — it's \"direct-to-chip liquid cooling is mandatory.\" Every existing data center that wants to run Rubin needs to retrofit. Cooling infrastructure lead times are 12-18 months. The window for ordering is now, not later.",
      "The M&A activity validates the thesis from the buy side. Ecolab acquired CoolIT Systems in March 2026 for an expected $550 million in revenue over the next 12 months. Trane Technologies acquired LiquidStack. Wilo signed a cooling partnership with DCX in April. When industrial conglomerates start acquiring specialized cooling companies, they're betting the same direction.",
      "Vertiv's backlog climbed to $9.5 billion with a new Nvidia partnership on standardized 12.5MW modular cooling blocks. nVent is launching new CDU products and opened a 117,000 sq ft manufacturing facility in Minnesota. Modine's data center revenues are exceeding $400 million per quarter, up 31% sequentially.",
      "No signal changes. BUY VRT, BUY NVT, HOLD MOD.",
      "--- The portfolio as a system ---",
      "The three theses were published as separate pieces. But the first week of tracking reveals that they're more entangled than I initially framed. The copper tariff doesn't just affect copper miners — it raises costs for transformer manufacturers. The transformer shortage doesn't just delay data centers — it delays cooling infrastructure orders. The cooling buildout doesn't just require thermal engineering — it requires copper piping and electrical connections that run through the same bottlenecks.",
      "This is the framing-vs-function pattern applied to the portfolio itself. The framing: three independent theses about three different bottlenecks. The function: one interconnected system where each constraint amplifies the others. A disruption at any layer — copper supply, transformer production, cooling capacity — cascades through the whole stack.",
      "That interconnection is why the portfolio is 9 of 10 green. When the underlying thesis is \"physical infrastructure is the constraint on a digital buildout,\" confirmation anywhere benefits everything. The risk runs the same way: if AI capex contracts sharply, all three layers de-rate together.",
      "For now, the structural story holds. The earnings season starting next week (GEV April 22, FCX April 23, PWR April 30) will provide the hardest data yet on whether backlog converts to revenue. That's the question that matters.",
    ],
    sources: [
      { title: "Half of Planned US Data Center Builds Delayed or Canceled", url: "https://www.tomshardware.com/tech-industry/artificial-intelligence/half-of-planned-us-data-center-builds-have-been-delayed-or-canceled-growth-limited-by-shortages-of-power-infrastructure-and-parts-from-china-the-ai-build-out-flips-the-breakers", author: "Tom's Hardware" },
      { title: "US AI Data Center Expansion Relies on Chinese Electrical Equipment", url: "https://www.bloomberg.com/news/features/2026-04-01/us-ai-data-center-expansion-relies-on-chinese-electrical-equipment-imports", author: "Bloomberg" },
      { title: "Eaton Invests $340M in US Transformer Production", url: "https://www.utilitydive.com/news/eaton-transformer-production-shortage-investment/739932/", author: "Utility Dive" },
      { title: "Quanta Services Investor Day: $2.4T TAM, EPS Targets Through 2030", url: "https://www.themarketsdaily.com/2026/04/04/quanta-services-investor-day-ceo-pegs-2-4t-tam-targets-21-60-26-75-eps-by-2030.html", author: "Markets Daily" },
      { title: "Southern Copper CEO Oscar Gonzalez Rocha Dies", url: "https://www.gurufocus.com/news/8790637/southern-copper-scco-announces-passing-of-ceo-oscar-gonzalez-rocha", author: "Guru Focus" },
      { title: "Tía María Project Under Review, Not Canceled", url: "https://www.gurufocus.com/news/8789972/southern-copper-scco-tia-maria-project-under-review-not-canceled", author: "Guru Focus" },
      { title: "Section 232 Copper Tariffs — Fact Sheet", url: "https://www.whitehouse.gov/fact-sheets/2026/04/fact-sheet-president-donald-j-trump-strengthens-tariffs-on-steel-aluminum-and-copper-imports/", author: "White House" },
      { title: "Grasberg Supply Shock to Plunge Copper Market into Deficit", url: "https://source.benchmarkminerals.com/article/grasberg-supply-shock-to-plunge-refined-copper-market-into-deficit-in-2026-benchmark-analysis-shows", author: "Benchmark Minerals" },
      { title: "Ecolab Acquires CoolIT Systems", url: "https://www.businesswire.com/news/home/20260319353197/en/Ecolab-to-Acquire-CoolIT-Systems,-a-Global-Leader-in-Advanced-Liquid-Cooling-for-Next-Gen-AI-Data-Centers", author: "BusinessWire" },
      { title: "Nvidia Rubin Cooling: Reality vs. Hype", url: "https://www.compassdatacenters.com/in-the-news/nvidia-rubin-liquid-cooling-reality-vs-hype/", author: "Compass Datacenters" },
    ],
  },
  {
    slug: "the-heat-wall",
    date: "2026-04-11",
    title: "The Heat Wall",
    excerpt:
      "AI's power gets delivered by transformers and carried by copper. Then it becomes heat. In January, Jensen Huang said Nvidia's next chips won't need water chillers — and cooling stocks crashed 21%. The market panicked about the wrong thing.",
    content: [
      "In January 2026, Jensen Huang stood on stage at CES and said something that wiped billions off cooling stocks in a single afternoon. Nvidia's next-generation Rubin chips, he explained, could be cooled with water at 45 degrees Celsius. At that temperature, no water chillers are necessary. The implication seemed clear: the cooling problem was being engineered away.",
      "Modine Manufacturing fell 21%. Trane Technologies dropped 11%. Johnson Controls lost 7.5%. Carrier Global slid. Bloomberg ran the headline. The narrative was immediate: if Nvidia can eliminate chillers, the cooling bottleneck disappears.",
      "Within weeks, every one of those stocks recovered. Modine is up 124% over the past twelve months. Vertiv, the dominant player in data center cooling infrastructure, is up 42% in 2026 alone. What happened?",
      "The market confused the framing with the function. Huang said no chillers. He didn't say no cooling. Removing chillers from the cooling loop means the water doesn't need to be mechanically refrigerated before it reaches the chips — a meaningful efficiency gain that saves roughly 6% of data center power consumption. But the water still needs to reach the chips. The liquid still flows through coolant distribution units, cold plates bonded to processors, piping infrastructure threaded through every rack. Direct-to-chip liquid cooling isn't optional at 100kW+ per rack. It's the only thing that works.",
      "This is the same framing-versus-function gap from the first two pieces in this series. The transformer bottleneck looked like a chip shortage until you traced the constraint to the grid. The copper squeeze looked like an energy transition until you traced the constraint to a metal. The cooling story looks like it's about temperature management. It functions as a plumbing problem — and plumbing at a scale no data center operator has ever attempted.",
      "The numbers are hard to overstate. The global data center liquid cooling market was $6.65 billion in 2025. It's projected to reach $29 billion by 2033 — a fourfold increase in eight years. The coolant distribution unit (CDU) segment alone is growing at 33% annually, from $1 billion to $7.7 billion, with lead times running 12–18 months for quality units. That lead time matters: you can't install AI racks without the cooling infrastructure already in place, and the infrastructure takes longer to build than to order the chips.",
      "Each layer of the AI infrastructure stack has the same structure. The digital layer (chips, models, software) is where the narrative lives. The physical layer (transformers, copper, cooling) is where the constraint lives. And within the physical layer, each bottleneck feeds the next: transformers deliver the power, copper carries it, and cooling dissipates what the compute turns it into — heat. Every watt that enters a GPU exits as thermal energy. A 100-megawatt data center is a 100-megawatt heater.",
      "The CES panic revealed exactly who has real exposure and who doesn't. The stocks that crashed hardest — Trane, Johnson Controls, Carrier — are traditional HVAC companies for whom data centers are one vertical among many. Chillers are their core product. Huang's comment hit them where it matters. But the companies building the liquid cooling infrastructure that replaces chillers — CDUs, cold plates, rear-door heat exchangers, the piping that threads through high-density racks — those are the ones whose addressable market actually expanded when Huang spoke. Moving from chiller-dependent cooling to direct-to-chip liquid cooling doesn't shrink the cooling market. It shifts it.",
      "Vertiv understood this before CES. Their Q4 2025 organic orders grew 252% year-over-year. Backlog: $15 billion. Book-to-bill ratio: 2.9x — for every dollar shipped, nearly three dollars booked. They're guiding $13.5 billion in 2026 revenue with 28% organic growth. Capital expenditure is stepping up from 2-3% to 3-4% of sales, with new factory locations coming online. They deployed $1 billion in strategic acquisitions in Q4 2025 alone. This is not a company worried about the cooling market shrinking.",
      "nVent, smaller and more focused, has roughly 30% of revenue from data centers and a deepening Nvidia partnership. Their next-generation CDUs and power distribution portfolios ship in the first half of 2026. At $21 billion market cap versus Vertiv's $113 billion, nVent offers higher growth leverage if liquid cooling adoption accelerates — which every industry forecast says it will.",
      "Modine, despite the CES crash, has a five-year order book and is commissioning new chiller lines as fast as it can build them — eight by fiscal year-end with a roadmap to twenty by early 2028. Margins in its Climate Solutions segment are running 20-23%. The market punished it for chiller exposure, but data center operators still need cooling at the facility level even when chip-level cooling shifts to liquid. Modine straddles both sides.",
      "The bear case is real and specific. If the AI capex cycle turns out to be a bubble — if the $660 billion in spending doesn't generate proportional revenue — then cooling demand falls with everything else. The bullwhip risk is significant: cooling stocks are priced for continued exponential growth. If hyperscaler orders slow, the multiple compression will be brutal. Vertiv at 10x price-to-sales is not cheap. And the CES episode showed how quickly sentiment can shift on a single executive's comment about thermal architecture.",
      "But the structural argument cuts the other direction. Even in a capex pullback, the data centers already under construction still need cooling. Vertiv's $15 billion backlog isn't speculative — it's signed orders. And rack densities are rising regardless of AI hype: enterprise computing, cloud workloads, and high-performance computing all generate more heat than they did five years ago. Liquid cooling isn't just an AI story. It's the direction computing is moving.",
      "--- What to do with this — data as of 2026-04-11 ---",
      "BUY: Vertiv Holdings (NYSE: VRT) — ~$295, market cap ~$113B. The dominant data center cooling and power infrastructure company. $15B backlog at 2.9x book-to-bill. Guiding $13.5B revenue in 2026 (+28% organic), adjusted EPS ~$6.20 (+43%). Q1 2026 earnings due April 22. 52-week range: approximately $100–$310. Expensive at 10x sales, but the backlog is locked in and the company is the closest thing to a pure-play on data center physical infrastructure. Buy for a multi-year hold; don't trade around earnings.",
      "BUY: nVent Electric (NYSE: NVT) — ~$131, market cap ~$21B. Roughly 30% data center revenue with growing Nvidia partnership. Next-gen CDU and liquid cooling portfolio shipping H1 2026. Smaller than Vertiv, which means higher growth leverage as liquid cooling adoption accelerates. Less analyst coverage, less crowded. The higher-beta play on the same thesis.",
      "HOLD: Modine Manufacturing (NYSE: MOD) — ~$239, market cap ~$12B. Five-year order book, margins expanding to 20-23%, aggressive capacity build. But the CES crash (-21% in a day) showed the stock's vulnerability to narrative shifts around chiller technology. Modine is genuinely well-positioned — it straddles facility-level and rack-level cooling — but the market treats it as a chiller stock. Hold if you own it. Buy on the next CES-style panic dip below $200.",
      "AVOID: Traditional HVAC companies (Trane Technologies, Johnson Controls, Carrier Global) as AI cooling plays. They have data center exposure, but it's a small portion of revenue, and their core product — chillers — is the component being displaced by direct-to-chip liquid cooling. Huang told you the direction at CES. Believe him on the technology even if the market's one-day reaction was wrong.",
      "The series so far: transformers deliver the power. Copper carries it. Cooling dissipates what it becomes. Each layer deeper, the investments get more physically tangible and the supply constraints get harder to solve with software. The market wants to price AI as a digital revolution. It keeps functioning as an industrial one.",
    ],
    sources: [
      { title: "Nvidia CEO Jensen Huang Tanked Data Center Cooling Stocks at CES", url: "https://www.fastcompany.com/91470119/nvidia-ceo-jensen-huang-unexpectedly-tanked-data-center-cooling-stocks-heres-why", author: "Fast Company" },
      { title: "Data-Center Cooling Stocks Sink After Nvidia CEO's CES Talk", url: "https://finance.yahoo.com/news/data-center-cooling-related-stocks-172732446.html", author: "Bloomberg" },
      { title: "Vertiv CEO: Liquid Cooling Capacity Growing 'Really, Really, Really Rapidly'", url: "https://247wallst.com/investing/2026/03/18/vertiv-ceo-liquid-cooling-capacity-growing-really-really-really-rapidly/", author: "24/7 Wall St" },
      { title: "Think It's Too Late to Buy Vertiv? Here's Why the $15 Billion Backlog Says Otherwise", url: "https://247wallst.com/investing/2026/04/10/think-its-too-late-to-buy-vertiv-heres-why-the-15-billion-backlog-says-otherwise/", author: "24/7 Wall St" },
      { title: "nVent Next Generation Liquid Cooling and Power Portfolios Coming 2026", url: "https://www.nvent.com/en-us/data-solutions/next-generation-liquid-cooling-and-power-portfolios-coming-2026", author: "nVent" },
      { title: "Modine: Structural Data Center Demand At Richer Margins", url: "https://seekingalpha.com/article/4862437-modine-structural-data-center-demand-at-richer-margins-maintain-buy", author: "Seeking Alpha" },
      { title: "Liquid Cooling the Next Supercycle Within the AI Supercycle", url: "https://www.fool.com/investing/2026/04/01/predict-liquid-cooling-next-supercycle-ai-stock/", author: "Motley Fool" },
      { title: "Data Center Liquid Cooling Market Report 2025-2033", url: "https://www.grandviewresearch.com/industry-analysis/data-center-liquid-cooling-market-report", author: "Grand View Research" },
      { title: "AI's Great Infrastructure Boom: Bullwhip or Building the Future?", url: "https://gadallon.substack.com/p/ais-great-infrastructure-boom-bullwhip" },
      { title: "Data Center Cooling Demand Will Outlast AI Bubble, Ecolab Says", url: "https://www.bloomberg.com/news/articles/2026-03-24/data-center-cooling-demand-will-outlast-ai-bubble-ecolab-says", author: "Bloomberg" },
    ],
  },
  {
    slug: "the-transformer-bottleneck",
    date: "2026-04-09",
    title: "The Transformer Bottleneck",
    excerpt:
      "Everyone frames AI as a digital revolution — chips, models, software. But in 2026, the actual bottleneck is hundred-year-old technology: power transformers. The framing is digital. The function is electrical.",
    content: [
      "In 2026, the five largest cloud and AI infrastructure providers — Microsoft, Alphabet, Amazon, Meta, and Oracle — have collectively committed to spending between $660 billion and $690 billion on capital expenditure. Nearly doubling 2025 levels. The vast majority is directed at AI compute, data centers, and networking.",
      "The framing of this spending is digital: faster chips, bigger models, smarter software. Nvidia's GPUs, OpenAI's models, the race to artificial general intelligence. The investment narrative is about intelligence — who will build it first, and who will profit from it.",
      "The function is different. Half of all planned data center projects globally are delayed or at risk — not because of chip shortages, not because of talent gaps, but because of power. Specifically: power transformers, switchgear, and grid connections. Lead times for large power transformers have stretched from 24-30 months (pre-2020) to as long as five years. In the European Union, waiting times for grid connections range from two to ten years.",
      "This is the framing-versus-function pattern I've been tracking across the garden's readings: what something appears to be is a poor guide to what it actually does. The AI revolution appears to be a software revolution. It functions as an electrical infrastructure revolution. The constraint isn't intelligence — it's the grid.",
      "The numbers clarify the gap. AI services generate roughly $25 billion in direct revenue today. That's about 4% of what's being spent on infrastructure. At current adoption rates, it may take companies six to eight years to break even on their 2026 investments. This is a 17-to-1 ratio of investment to revenue. Whatever AI eventually becomes, right now its function is the largest electrical infrastructure buildout since rural electrification.",
      "Who benefits from this? Not necessarily the companies building AI. Marc Bara argues in \"The Picks and Shovels Trap\" that the traditional gold rush analogy is misleading: the money circulates in a closed loop. OpenAI raises billions from Microsoft, then spends it on Microsoft Azure. Anthropic raises billions from Amazon, then spends it on AWS. GPU rental rates have fallen 50-70%. The neocloud companies building GPU clusters may be building assets that hyperscalers will acquire at distressed prices once valuations collapse.",
      "The companies that benefit most predictably are the ones making the equipment that every data center requires regardless of which AI company wins. Power transformers. Switchgear. Transmission infrastructure. Grid connections. The boring stuff.",
      "GE Vernova, spun off from General Electric, reported electrification revenue projected to surge 44% in 2026 to $13.9 billion. Its backlog is expected to reach $200 billion by 2028. Hyperscalers now account for over one-third of recent orders. In February 2026, GE Vernova completed a $5.3 billion acquisition of Prolec GE — a direct response to the global shortage of grid equipment.",
      "Hitachi Energy is investing over $1 billion in US manufacturing, including a $457 million facility in Virginia that will become the nation's largest large power transformer plant by 2028. Siemens Energy is building its first US large power transformer plant in North Carolina. Eaton has committed $1.2 billion to capacity expansion for high-voltage equipment.",
      "Quanta Services, which builds the grid infrastructure these manufacturers produce, entered 2026 with a $39.2 billion backlog. JPMorgan upgraded the stock to overweight, noting the company is uniquely positioned to serve large-load customers like Amazon and Google.",
      "The structural advantage of these companies: they win in almost every scenario. If AI capex continues growing, data centers need more transformers and grid equipment. If AI capex contracts, the existing backlog is so deep (3-5 year lead times) that revenue is locked in for years. And grid demand extends far beyond AI — electric vehicles, renewable energy integration, industrial reshoring, and general grid modernization all require the same equipment. Even if the AI bubble deflates, the electrical infrastructure buildout doesn't stop.",
      "The risk is real but specific: a sharp AI capex pullback could slow new orders beyond existing backlogs. Analysts warn that if $660 billion in spending doesn't translate into proportional revenue, the market could see a correction in the second half of 2026. But correction in hyperscaler stocks is not the same as correction in their suppliers' revenue — the orders are already placed, the equipment already in production.",
      "There's a parallel to Benedict Springbett's essay about Munich's through-running tunnel. The tunnel's surface description — one short connection — completely misrepresented its systemic role. It was the missing piece that made twelve disconnected lines into a unified network. Power transformers have the same character. They sound boring, incremental, old-fashioned. But they are the binding constraint on a $690 billion investment cycle. Without them, nothing else works. The framing makes them invisible. The function makes them essential.",
      "--- What to do with this — data as of 2026-04-09 ---",
      "BUY: Eaton (NYSE: ETN) — ~$369, market cap ~$141B. The best entry point of the three. Investing $1.2 billion in high-voltage equipment capacity expansion targeting the data center power gap. Analyst consensus: Buy, 12-month target ~$401 (+9%). 52-week range: $245–$408. Currently mid-range, not overextended. Broader industrial exposure means less downside if AI capex specifically slows — Eaton sells into EVs, industrial automation, and building infrastructure too.",
      "BUY: GE Vernova (NYSE: GEV) — ~$940, market cap ~$253B. The dominant US grid equipment player. Electrification revenue projected up 44% in 2026 to $13.9 billion. Backlog expected to reach $200 billion by 2028. Completed $5.3 billion Prolec GE acquisition to address transformer shortage. 52-week range: $303–$979. The stock has tripled in a year, so you're paying a premium — but the backlog is locked in and hyperscalers account for over a third of orders. Buy on any meaningful dip rather than chasing at all-time highs.",
      "HOLD/WATCH: Quanta Services (NYSE: PWR) — ~$580, market cap ~$83B. Builds the grid infrastructure that the manufacturers produce — installs transformers, runs transmission lines, connects substations. Backlog surged 27.5% to $44 billion. But: PE ratio of 86 and 112% price increase over the past year means a lot of growth is already priced in. Strong company, expensive entry. Wait for a pullback below $500 or buy a small position and add on dips.",
      "AVOID: Pure-play AI infrastructure companies (CoreWeave, Lambda Labs, Cerebras). GPU rental rates have fallen 50–70%. These companies are building assets that hyperscalers may acquire at distressed prices. The picks-and-shovels logic doesn't work when the gold miners are building their own shovels.",
      "Why these win in most scenarios: if AI capex keeps growing, every new data center needs their equipment. If AI capex contracts, existing backlogs (3–5 year lead times) protect revenue for years. Beyond AI entirely — EVs, renewables, reshoring, and aging grid replacement all need the same transformers and switchgear. The main risk: a severe, multi-year freeze in all new electrical infrastructure orders simultaneously. Possible but unlikely while the grid is aging and electrification is accelerating across every sector.",
      "The pattern holds: AI appears to be about intelligence. Right now, it's about electricity. Buy the electricity.",
    ],
    sources: [
      { title: "AI Capex 2026: The $690B Infrastructure Sprint", url: "https://futurumgroup.com/insights/ai-capex-2026-the-690b-infrastructure-sprint/" },
      { title: "Why AI Companies May Invest More than $500 Billion in 2026", url: "https://www.goldmansachs.com/insights/articles/why-ai-companies-may-invest-more-than-500-billion-in-2026", author: "Goldman Sachs" },
      { title: "The Picks and Shovels Trap", url: "https://medium.com/@marc.bara.iniesta/the-picks-and-shovels-trap-ais-200-billion-subsidy-for-big-tech-de1d216ce9ad", author: "Marc Bara" },
      { title: "Data Center Power Crisis 2026: The Grid Bottleneck", url: "https://enkiai.com/data-center/data-center-power-crisis-2026-the-grid-bottleneck/" },
      { title: "Power Hardware Shortages Are Delaying AI Data Centre Expansion", url: "https://dig.watch/updates/power-hardware-shortages-are-delaying-ai-data-centre-expansion-despite-record-investment", author: "Digital Watch Observatory" },
      { title: "Here's Why GE Vernova Stock Keeps Soaring in 2026", url: "https://www.fool.com/investing/2026/02/07/heres-why-ge-vernova-stock-keeps-soaring-in-2026/", author: "Motley Fool" },
      { title: "Top AI Infrastructure Stocks For 2026 Industrial Super-Cycle", url: "https://www.benzinga.com/trading-ideas/long-ideas/25/12/49572927/top-ai-infrastructure-stocks-for-2026-industrial-super-cycle", author: "Benzinga" },
      { title: "Transformers in 2026: Shortage, Scramble, or Self-Inflicted Crisis?", url: "https://www.powermag.com/transformers-in-2026-shortage-scramble-or-self-inflicted-crisis/", author: "Power Magazine" },
    ],
  },
  {
    slug: "the-copper-squeeze",
    date: "2026-04-10",
    title: "The Copper Squeeze",
    excerpt:
      "The transformer bottleneck is downstream of a deeper one: copper. Every transformer, every EV, every data center, every solar panel needs it. New mines take 20-30 years to open. Demand is rising 50% by 2040. Supply can't keep up.",
    content: [
      "The previous research piece identified power transformers as the binding constraint on AI's $690 billion capex cycle. But transformers themselves are made of copper — thousands of tonnes of it. So are the transmission lines that connect data centers to the grid, the busbars inside the data centers, the cables in every EV, and the wiring in every solar installation. Follow any electrification story deep enough and you arrive at the same place: copper.",
      "The framing of the energy transition is about end products — solar panels, batteries, electric vehicles, AI chips. The function requires a metal that humans have been mining for 10,000 years and are now running short of.",
      "S&P Global published an updated study in January 2026 warning of a \"substantial shortfall\" in copper supply. The numbers: global copper demand is projected to reach 42 million metric tonnes by 2040, a 50% increase from current levels. But global production is expected to peak at 33 million metric tonnes in 2030 and then decline as existing mines deplete. Only 70% of projected 2035 demand can be met from currently planned supply. The gap isn't a temporary blip — it's structural.",
      "In 2026 specifically, the market is shifting from a slight surplus in 2025 to a deficit estimated between 150,000 and 400,000 tonnes, depending on whose models you trust. UBS forecasts the larger number. The deficit is driven by converging demand from AI data centers, electric vehicles, grid modernization, defense spending, and industrial reshoring — all competing for the same metal simultaneously.",
      "The AI demand alone is staggering. A single 100-megawatt data center campus requires several thousand tonnes of copper — roughly 27 to 33 tonnes per megawatt of installed capacity. That copper goes into power distribution, cooling systems, networking, and the transformers and switchgear that connect the facility to the grid. AI data centers could consume over 500,000 tonnes of copper annually by 2030. For context, total global copper production is about 22 million tonnes per year. AI alone would claim over 2% of world supply.",
      "Electric vehicles add another layer. An EV requires 80-100 kilograms of copper, roughly 3-4 times more than a conventional car. As EV adoption accelerates, automotive copper demand scales with it. And every EV needs charging infrastructure — more copper in cables, transformers, and grid connections.",
      "The supply side can't respond quickly. Opening a new copper mine takes 20-30 years from discovery to production. In 2026, major unplanned disruptions at the Grasberg mine in Indonesia and Kamoa-Kakula in the DRC are further limiting output. Even the mines currently under development won't meaningfully add supply before 2028-2029. You cannot build your way out of a copper deficit on any timeline that matters for the current investment cycle.",
      "This creates a structural price floor. J.P. Morgan expects copper to average roughly $12,075 per tonne in 2026. Bank of America forecasts $11,313 per tonne in 2026 rising to $13,501 in 2027. Goldman Sachs sees copper reaching $15,000 per tonne by 2035. These forecasts reflect a simple reality: demand is growing faster than supply, and supply cannot be created quickly.",
      "The connection to the transformer bottleneck is direct. The previous piece showed that power transformers are the binding constraint on data center construction, with lead times stretching to 3-5 years. Those transformers are wound with copper. If copper supply tightens further, transformer production slows further, and the entire AI infrastructure buildout slows with it. The bottleneck compounds.",
      "--- What to do with this — data as of 2026-04-10 ---",
      "BUY: Freeport-McMoRan (NYSE: FCX) — ~$66, market cap ~$95B. The largest copper producer in the Americas, responsible for 70% of US refined copper production. Produced 3.5 billion pounds of copper in 2025. Analyst consensus: Buy, average 12-month target ~$67 with a high estimate of $81. 52-week performance: up 115%. Pure-play copper exposure with significant gold and molybdenum byproducts that subsidize copper production costs. The most direct way to bet on rising copper prices.",
      "BUY: Southern Copper (NYSE: SCCO) — ~$178, market cap ~$137B. The fifth-largest copper producer globally with the lowest production costs in the industry and the largest copper reserves of any publicly traded company. Has approved expansion projects adding 156,000 tonnes of annual output by 2027. Low costs mean higher margins as copper prices rise, and the reserve base means decades of production ahead. Premium valuation reflects the quality, but the cost advantage is real.",
      "BUY: Global X Copper Miners ETF (COPX) — ~$82, AUM ~$6.9B. Diversified exposure to copper miners globally, tracking the Solactive Global Copper Miners index. Up 144% over the past year. This is the simplest way to get broad copper exposure without picking individual miners. Holds Freeport, Southern Copper, and dozens of smaller miners. If you want one position instead of three, this is it.",
      "HOLD/WATCH: BHP Group (NYSE: BHP) — ~$77, market cap ~$186B. The world's largest mining company, actively shifting strategic focus toward copper. But copper is only one segment alongside iron ore and coal, so the stock won't move purely on copper prices. Better as a diversified resources holding than a copper bet. Buy if you want broader commodity exposure with copper upside.",
      "AVOID: Copper futures or leveraged copper ETFs for long-term positions. Goldman Sachs warns that short-term copper prices may pull back from record highs in 2026 before the structural deficit fully materializes. The thesis is about a multi-year supply gap, not a short-term price spike. Buy miners who benefit from sustained high prices, not instruments that punish you for timing volatility.",
      "The pattern from the first piece extends: AI appears to be about software. It functions as an electrical infrastructure buildout. And electrical infrastructure functions as a demand shock on industrial metals — above all, copper. Each layer you go deeper, the investments get more boring and the supply constraints get harder to solve. Buy the boring thing that everything else depends on.",
    ],
    sources: [
      { title: "Copper in the Age of AI: Challenges of Electrification", url: "https://www.spglobal.com/en/research-insights/special-reports/copper-in-the-age-of-ai", author: "S&P Global" },
      { title: "Substantial Shortfall in Copper Supply Widens (Jan 2026)", url: "https://press.spglobal.com/2026-01-08-Substantial-Shortfall-in-Copper-Supply-Widens-as-the-Race-for-AI-and-Growing-Defense-Spending-Add-to-Accelerating-Demand,-New-S-P-Global-Study-Finds", author: "S&P Global" },
      { title: "Copper Price Forecast 2026: Supply Deficit, AI Demand & Market Outlook", url: "https://www.leanrs.com/insights/copper-price-forecast-2026-supply-deficit-ai-demand-market-outlook" },
      { title: "Copper Market Outlook", url: "https://www.jpmorgan.com/insights/global-research/commodities/copper-outlook", author: "J.P. Morgan" },
      { title: "Why Record-High Copper Prices Aren't Forecast to Last", url: "https://www.goldmansachs.com/insights/articles/why-record-high-copper-prices-arent-forecast-to-last", author: "Goldman Sachs" },
      { title: "AI Data Centers Could Consume Half a Million Tons of Copper Annually by 2030", url: "https://www.usfunds.com/resource/ai-data-centers-could-consume-half-a-million-tons-of-copper-annually-by-2030/", author: "US Funds" },
      { title: "5 Best Copper Stocks for 2026", url: "https://www.fool.com/investing/stock-market/market-sectors/materials/metal-stocks/copper-stocks/", author: "Motley Fool" },
      { title: "The Red Metal's AI Revolution: Copper ETFs Poised for a Strong 2026", url: "https://www.nasdaq.com/articles/red-metals-ai-revolution-copper-etfs-poised-strong-2026", author: "Nasdaq" },
    ],
  },
];

export function getAllResearch(): ResearchPiece[] {
  return pieces;
}

export function getResearch(slug: string): ResearchPiece | undefined {
  return pieces.find((p) => p.slug === slug);
}
